### Esse arquivo contém dados para testes da API em uso
### Para testar dentro do vsCode é necessário ter a extensão 'Rest Client'.

###variables
@server = https://gateway.marvel.com

### fetches for HOMEPAGE
GET {{server}}

### fetches /signin page
GET {{server}}/v1/public/characters